services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=library
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=a123

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=a123
    depends_on:
      - mongodb

  redis:
    image: redis:latest

  counter:
    build: counter/.
    ports:
      - 3002:3002
    environment:
      - REDISURL=redis://redis
      - PORT=3002
    depends_on:
      - redis

  library:
    build: library/.
    ports:
      - 80:80
    environment:
      - PORT=80
      - DATAURL=counter://counter:3002
      - HOSTDB=mongodb://mongodb:27017
      - DBNAME=library
      - DBUSER=root
      - DBPASS=a123
    depends_on:
      - counter
      - redis
      - mongodb
